# Generated by Django 4.2 on 2026-01-25 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('IMPORT', 'Импорт'), ('VALIDATE', 'Валидация'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление')], max_length=50, verbose_name='Тип операции')),
                ('filename', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Обработано элементов')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выполнения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-performed_at'],
            },
        ),
    ]
