# Generated by Django 4.2 on 2026-01-25 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('xml_filename', models.CharField(blank=True, max_length=500, null=True, verbose_name='XML файл')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FolderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата привязки')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Документ')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Привязка документа к папке',
                'verbose_name_plural': 'Привязки документов к папкам',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderdocument',
            unique_together={('folder', 'document')},
        ),
    ]
