# Generated by Django 5.2.10 on 2026-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_code'),
        ('structures', '0002_alter_folder_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш файла'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_a7f76e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['code'], name='documents_d_code_ec4445_idx'),
        ),
        migrations.AddIndex(
            model_name='folderdocument',
            index=models.Index(fields=['folder', 'document'], name='documents_f_folder__fa9b72_idx'),
        ),
    ]
