# Generated by Django 4.2 on 2026-01-25 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('materialized_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Путь')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Атрибуты')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название структуры')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['content_hash'], name='structures__content_08284c_idx'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='structures.folder', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='folder',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='structures.structure', verbose_name='Структура'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['materialized_path'], name='structures__materia_95fbab_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['structure', 'parent'], name='structures__structu_7a4594_idx'),
        ),
    ]
