# Generated by Django 5.2.10 on 2026-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('structure', 'code'), name='unique_folder_code_per_structure'),
        ),
    ]
